### ISSUE TITLE
Add support SameSite cookie attribute

### ISSUE THREAD

**Issue by Lebed71** [jshttp/cookie#102]
In Google Chrome, starting with version 80, the installation of the SameSite = Lax attribute is enabled by default. This disrupts the operation of many sites and requires redefinition, but this package does not support this attribute.

Proof link - https://chromestatus.com/feature/5088147346030592

**Comment by dougwilson** [comment]
Support was added 11 months ago https://github.com/jshttp/cookie/blob/master/HISTORY.md#040--2019-05-15
