### ISSUE TITLE
Max-Age are taking Infinity this is not valid for http specification

### ISSUE THREAD

**Issue by smondal** [jshttp/cookie#103]
Max-Age are showing "Infinity", If I give big number. This is not a valid value for Max-Age field.
https://tools.ietf.org/html/rfc6265#section-5.2.2

cookie.serialize('name', String("sandip"), {httpOnly: "sandip", maxAge: 60 ** 60 ** 24, expires: new Date()})
'name=sandip; Max-Age=**Infinity**; Expires=Mon, 13 Apr 2020 15:39:35 GMT; HttpOnly'

**Comment by dougwilson** [comment]
Thanks, definitely a bug. It should throw on `Infinity` provided as `maxAge` option since there is no way to serialize that.
