### ISSUE TITLE
cookie.parse treats the Path parameter as a cookie

### ISSUE THREAD

**Issue by nigel-smk** [jshttp/cookie#106]
I would expect 
```
cookie.parse('cookie_key=cookie_value; Path=/; HttpOnly')
```
to return
```
{
  cookie_key: 'cookie_value'
}
```
but it instead returns
```
{
  cookie_key: 'cookie_value',
  Path: '/'
}
```

As I understand it, `Path` is a meta data directive, not a cookie value https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie

**Comment by dougwilson** [comment]
Hello! The `cookie.parse` function does not accept the `Set-Cookie` format. You can read more about this function in our documentation https://github.com/jshttp/cookie#cookieparsestr-options 

> Parse an HTTP Cookie header string and returning an object of all cookie name-value pairs
