### ISSUE TITLE
[Feature] get expiry date or time for a cookie

### ISSUE THREAD

**Issue by raminjafary** [jshttp/cookie#113]
I think it would be great if there was a way to get expiry date or time for a given cookie. When one is using SSR, there are times one need to know expiration date to schedule some tasks on the client.
I want to work on this issue if you are still maintaining this module, or does it fit in your plan scope.

**Comment by dougwilson** [comment]
Unfortunately this is not possible to do; the only data the client sends to the server is the cookie's name and value.
