### ISSUE TITLE
Missing Secure and HttpOnly flags on parsed cookies

### ISSUE THREAD

**Issue by lewispham** [jshttp/cookie#115]
It looks like cookie.parse is bypassing all values whose dont follow the `key=value` format. But shouldn't they be parsed with a boolean output instead?

Reproduce
```
cookie.parse (`foo=bar; HttpOnly; Secure`); 
```
Current output
```
{ foo: "bar" };
```

Expected output
```
{ foo: "bar", Secure: true, HttpOnly: true }
```

**Comment by dougwilson** [comment]
From the docs (https://github.com/jshttp/cookie#cookieparsestr-options):

> Parse an HTTP Cookie header string and returning an object of all cookie name-value pairs. 

The `Cookie` header does not have httponly and secure flags like you are showing; that is the `Set-Cookie` header, which this module does not provide a parsing function for.
