### ISSUE TITLE
cookie.parse() domain= parsing not RFC-compliant

### ISSUE THREAD

**Issue by bnoordhuis** [jshttp/cookie#118]
**removes security report**

**Comment by dougwilson** [comment]
Please report security issues privately so we have a chance to properly evaluate them and come up with a fix to release.

**Comment by dougwilson** [comment]
I would add that `cookie.parse`, as outlined in our README (https://github.com/jshttp/cookie#cookieparsestr-options) is only for the `Cookie` header, but you referenced the `Set-Cookie` header parsing spec:

> Parse an HTTP Cookie header string and returning an object of all cookie name-value pairs. The str argument is the string representing a Cookie header value and options is an optional object containing additional parsing options.

**Comment by bnoordhuis** [comment]
> Please report security issues privately so we have a chance to properly evaluate them and come up with a fix to release.

Consider adding the relevant info to the README because there's currently no way to divine that.
