### ISSUE TITLE
How to use this library in aws lambda

### ISSUE THREAD

**Issue by MeRahulAhire** [jshttp/cookie#126]
Im trying to figure out how to send and accept cookies in aws lambda but I didn't any prominent examples. so just wanted to know that how can I use this in lambda to set cookies in headers and also parse incoming cookies? 

Thanks..

**Comment by dougwilson** [comment]
I have not used AWS Lambda so not sure.

**Comment by MeRahulAhire** [comment]
No worries, Thanks...
