### ISSUE TITLE
ESM version

### ISSUE THREAD

**Issue by benmccann** [jshttp/cookie#127]
There was some previous discussion of this in https://github.com/jshttp/cookie/issues/87. However, I wanted to raise the issue since the JavaScript landscape has changed in the time since then and there are some considerations that were not raised in the original thread

Unbundled development is becoming very popular using tools like Snowpack, Vite, and WMR. These tools serve code in an unbundled fashion using purely ESM. Any library that is not distributed as ESM must be converted to ESM by these tools. That can be a somewhat error-prone process and in fact Vite currently chokes on this library (https://github.com/vitejs/vite/issues/2579). Those issues should be fixed in the development tools themselves, though we would avoid the issue if `cookie` were distributed in ESM. However, even if this issue is fixed, the lack of an ESM version means that development with these tools is slower because they must convert the library to ESM on first run of the project. It would be a better development experience to do the conversion just once before distributing the library rather than making every user do the conversion each time they run `npm install`

ESM is the standard and Node can now handle ESM natively. Node 8 and 10 support it via the `--experimental-modules` flag while Node 12 and newer support if out-of-the-box. At the end of this month, Node 10 will go EOL meaning every supported version of Node will support ESM out-of-the-box. It's quite possible at this point that it's no longer necessary to distribute a CJS version. However, if it's still preferred to support these older versions of node without requiring an extra CLI flag, it would be fairly straightforward to setup Rollup or some other process to distribute both a CJS and ESM version in the package.

Finally, supporting ESM would allow the library to be used in the browser and in isomorphic apps. This may not be something we wish to commit to supporting, but it could be a nice side-effect that it would be allowed

I'm happy to send a PR for this, but thought I'd check whether there's any openness to the idea first

**Comment by dougwilson** [comment]
Hi @benmccann thanks for opening this issue! I don't see any reason why we cannot add ESM support, though there are a couple caveats here:

1. This module's goal is to support as many Node.js versions as possible, so there is no dropping almost any of the Node.js support in the foreseeable future, especially since this module is a part of Express.js and it needs to continue to support that.
2. Introducing a build step like rollup in this module to continue CJS is not just not going to be acceptable. I'm sure there must be some method to support CJS and ESM without that, as I believe I have seen other modules do this, so adding complication and the ability for security compromises in the build process is just not going to really be a good solution.

I hope that provides some constraints around the conversation. I think if we work together, someone who knows how to implement ESM can help add it to this module with the above constraints intact.

**Comment by benmccann** [comment]
Thanks for the quick response!

Regarding the build step, I see two options:
- copy/paste all the code. future changes would need to update both versions
- maintain only one version, but create the second version with some sort of build step. This doesn't have to be Rollup. It could be a simple `.js` node script that does a copy and then find and replace. A shell script might be a bit less robust to changes in the source and could possibly need to be tweaked along with the source, but would not require any new dependencies in the build process

Thoughts?

**Comment by dougwilson** [comment]
So the first option is definately not appealing, as you're effectively describing two different modules as far as effort goes. It is easy enough to forget to update docs in a PR, just think of the two different implementations drifting apart.

The second could work. The main issue with the build processes are two fold: (1) pulling in things from npm that typically have `^` or similar dependencies allows for attacks on dependency changes to affect the build (I think there was a crypto coin client this happened to, even) and (2) many of the security vendors that state at the Express.js source code explicitly want us to have the files in the tarball on npm to be the exact files checked into the github repository at the commit hash that is in the npm metadata.

**Comment by benmccann** [comment]
(1) We could definitely have a conversion script without adding and dependencies or pulling anything else in from npm
(2) This one is trickier. We could require developers to run the conversion script and check in the converted version. Maybe setup a precommit hook. Or add a check on the CI to see if one file is updated that they both are

**Comment by dougwilson** [comment]
Cool. Yea, I'm trying to learn more about the current landscape, and figure https://nodejs.org/api/packages.html#packages_dual_commonjs_es_module_packages is the most up-to-date information. I see in there is says:

> Such a package would be usable by any version of Node.js, since import can refer to CommonJS files

So it sound like you can indeed `import` a CJS module, which seems different than in the past (maybe? I haven't really used it much).

How exactly is Node.js choking on this module? Maybe it could help to provide some kind of minimally-reproducible example of what the goal is here (I mean, we'd need to have it to add tests anyhow)?

**Comment by dougwilson** [comment]
P.S. it seems like making it work as ESM export would be as straight forward as using conditional exports and then the ESM module would be something like
```js
import cjsModule from './index.js';
export const parse = cjsModule.parse;
export const serialize = cjsModule.serialize;
```

**Comment by benmccann** [comment]
Yeah, Node can handle it just fine. It's not Node that's choking on it, but rather Vite (https://github.com/vitejs/vite/issues/2579). The choking part should be fixed in Vite, but even if it is fixed there then Snowpack / Vite / WMR still have the extra step of needing to convert the CJS to ESM when you first run them which makes things slower than necessary.

> import cjsModule from './index.js';

What's `index.js` in this case? I think that we really need a CJS and ESM version of `index.js` and don't want to mix-and-match.

**Comment by dougwilson** [comment]
> What's index.js in this case? 

It's just the current file in this repo. It could be renamed `.cjs` but I'm not sure if that will work in the old Node.js versions, but I haven't tried yet. This is following how Node.js says to make a duel module in their own documentation. Why would we not follow the Node.js documentation? Is there an issue doing the above? If so, what, specially, is the issue?

**Comment by dougwilson** [comment]
Oh, I see, looking at the Vite issue (sorry I didn't fully read it in your first post), it sounds like the issue is as straight forward as using `module.exports` instead of just the plain `exports`. I mean, using `module.exports` is the style I prefer on my own modules anyway, and the vast majority of the module in this organization use that style. So it seems like the issue could be fixed even easier than it sounded like. If I'm missing something here, let me know, but I believe that is what I'm reading in the issue you referenced.

**Comment by benmccann** [comment]
> It sounds like the issue is as straight forward as using `module.exports`

Two people later on in the thread said that changing it to `module.exports` didn't work for them (https://github.com/vitejs/vite/issues/2579#issuecomment-814499324). I just tested as well and can confirm that didn't work

>  This is following how Node.js says to make a duel module in their own documentation. Why would we not follow the Node.js documentation? Is there an issue doing the above? If so, what, specially, is the issue?

Oh, sorry, I didn't read [the docs](https://nodejs.org/api/packages.html#packages_approach_1_use_an_es_module_wrapper) close enough. I've never seen it done this way before, but that does work! It seems to only work if we rename `index.js` to `index.cjs` though. Also, the docs say that `main` is supported in all versions of Node, so this should work on old versions as well: https://nodejs.org/api/packages.html#packages_package_entry_points

**Comment by benmccann** [comment]
My earlier testing was wrong. I can't figure out how to make this work with Vite no matter what I do. It seems better to focus on fixing Vite
