### ISSUE TITLE
how to set multiple cookies in response?

### ISSUE THREAD

**Issue by natashajaved** [jshttp/cookie#129]

**Comment by dougwilson** [comment]
This is a low level library that simply outputs the string header. Please refer to the documentation regarding the http library you are using on how to set multiple response headers.

**Comment by floriansenat** [comment]
For setting multiple cookies with nodejs with `setHeader` you have to use an array as the value, like so :

```js
res.setHeader('Set-Cookie', [ cookie.serialize('name', 'value'), cookie.serialize('name2', 'value2' ])
```
[Offical documentation](https://nodejs.org/dist/latest-v14.x/docs/api/http.html#http_response_setheader_name_value)
