### ISSUE TITLE
Signed cookie

### ISSUE THREAD

**Issue by fmenis** [jshttp/cookie#131]
Hi!
I can't see the possibility of sign the cookie (when created) and check its signature (when parsed).
May I ask why this feature is not present?
It's present, for example, in the [fastify-cookie](https://github.com/fastify/fastify-cookie) package.

**Comment by dougwilson** [comment]
Hello, this library is designed as a low level library to parse and stringify the cookie according to the http spec. Signatures and encryptions can be done many ways. This library is meant to be built upon by another library to add such a feature, by for example, fastify-cookie, which uses this module:

https://github.com/fastify/fastify-cookie/blob/2f3d691c54b87b942471c0c5c45b23fbae898bb5/package.json#L49

**Comment by fmenis** [comment]
@dougwilson I understand, thanks for your quick response.
