### ISSUE TITLE
Uncaught SyntaxError: The requested module '/node_modules/cookie/index.js?v=f70d5086' does not provide an export named 'default'

### ISSUE THREAD

**Issue by n4an** [jshttp/cookie#134]
Uncaught SyntaxError: The requested module '/node_modules/cookie/index.js?v=f70d5086' does not provide an export named 'default'

**Comment by dougwilson** [comment]
Hello, ans sorry you are having trouble. This is a CJM style module, not a ESM one. That error is because you are trying to use it as ESM. You need to use as CJM.

**Comment by dougwilson** [comment]
Hello, and sorry you are having trouble. This module does not provide a default export; it provides two named exports: `parse` and `serialize`.
