### ISSUE TITLE
Typescript error ts(7016)

### ISSUE THREAD

**Issue by shinokada** [jshttp/cookie#135]
Importing cookie shows a Typescript error:

```
import { parse } from 'cookie';
```

Could not find a declaration file for module 'cookie'. '/Users/shinichiokada/Svelte/svelte-auth-typescript/node_modules/.pnpm/cookie@0.4.2/node_modules/cookie/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/cookie` if it exists or add a new declaration (.d.ts) file containing `declare module 'cookie';`ts(7016)

I tried:

```
npm i --save-dev @types/cookie
```

It returns npm ERR!.

**Comment by dougwilson** [comment]
The package is there: https://www.npmjs.com/package/@types/cookie

If you are having teouble using npm to install it, please contact npm support.
