### ISSUE TITLE
Feature request: Add ability to easily get the name and value of unparsed cookie string

### ISSUE THREAD

**Issue by markcellus** [jshttp/cookie#139]
Hello! Really love this package. Thanks for creating it! ❤️ 

Came here to request a new feature be added to the package. There doesn't currently seem to be a way to grab the key and value from a cookie string.

Given this cookie:

```
foo=bar; Domain='my/path'; Secure=; HttpOnly=;
```

I'd like to be able to easily get the key (`foo`) and the value (`bar`) so that I can pass them to other apis that need them.  Something that will give me the same object that gets returned from [`cookie.parse()`](https://github.com/jshttp/cookie/tree/v0.4.2#cookieparsestr-options)--but just without the name and value being mixed with attributes in the object. Like this:

```js
const niceObject = {
  key: 'foo',
  value: 'bar',
  attributes: {
    domain: 'my/path',
    secure: true,
    httpOnly: true
  }
}
```

For instance, if I wanted to take the cookie and add it to an Express response, I'd simply pass the key and value to [`res.cookie()`](https://expressjs.com/en/4x/api.html#res.cookie).

```js
const { key, value, attributes } = niceObject;
const { domain } = attributes;
res.cookie(key, value, {domain}) 
```
#67 was opened asking for this feature (perhaps mistakenly thinking the lack of it was a bug) but not sure why it was closed or why the comment I left on it got minimized or why the thread was locked right after. 😕 

Is this a feature that can be added to the package?

**Comment by dougwilson** [comment]
Hello! It looks like what you are trying to parse is the value of a set-cookie header. This is already available, just as a separate package: https://www.npmjs.com/package/set-cookie-parser

I hope that helps!

**Comment by markcellus** [comment]
Ah ok. Wasnt aware that exists. Thanks!
