### ISSUE TITLE
Unicode regex causing error on Safari frontend

### ISSUE THREAD

**Issue by Noitidart** [jshttp/cookie#141]
Is there an alternative to this here:

```
var fieldContentRegExp = /^[\u0009\u0020-\u007e\u0080-\u00ff]+$/;
```

It is crashing frontends like this issue here - https://github.com/andreizanik/cookies-next/issues/16 - the cookies-next package use the cookie package in fronted as Next.js is a server-side render framework. Is it possible to safely use this in frontend? Or

**Comment by dougwilson** [comment]
Hello, and sorry for the issue. Since this is a Node.js module it doesn't explicitly support web browsers. But what exactly is the issue with the regular expression? It seems valid to me, even going back and looking at the ECMA spec.

**Comment by Noitidart** [comment]
Thanks for the fast reply! Ah you're right, I'll have to bring it up with the cookies-next package to see if we can somehow make it safer.

Yeah it's real interesting  caniuse says it's ok to use unicode in iOS 10 Safari and up. 

For some reason the errors I see in Sentry are these:

```
Invalid regular expression: invalid escaped character for unicode pattern
```

And:

```
Unexpected token '{'. Expected '(' to start a 'catch' target.
```

I'm going to try to do a fiddle to try to figure out why its not working. Thanks so much for being so supportive to help find the issue here. I don't mind at all whenever you're ready to close this, I'll keep sharing my findings and what work goes on in that other package, really appreciate your genuine concern.

**Comment by Noitidart** [comment]
I just tested a fiddle, that regex works, very interesting. I'll close this, I'll let you know what i discover :)

**Comment by Noitidart** [comment]
Actually figured out it was another package excuse this please. Other issue - https://github.com/anantoghosh/react-linkify-it/issues/21 - thanks for hanging it with me!
