### ISSUE TITLE
Should expires be optional?

### ISSUE THREAD

**Issue by bdombro** [jshttp/cookie#142]
I notice that you added validation on expires with v5.0.0 -- this sadly broke my repo which sets a maxAge and does not set an expires. This bug took me an entire day to pinpoint because it was many layers deep in my dependencies and my dependencies didn't allow the error to bubble well >_<.

My question: is expires really required? I feel like it worked fine before when it wasn't.\

Commit in quesiton: https://github.com/jshttp/cookie/commit/042073f1d679b9c7fb7d64660d3c6d372bd1f468

**Comment by dougwilson** [comment]
Hi, very sorry about that! Our tests do indicate that it is indeed optional, and there is no v5.0.0 of this module, which seems odd. Can you paste code that only uses this module and shows you not passing in `expires` but receiving an error? Also the exact error message, ideally with a stack trace, would be helpful as well!

The commit you referenced just validates that the value passed in to `expires` is a date, shouldn't be requiring that you provide expires.

**Comment by dougwilson** [comment]
If it helps, here is our test suite testing setting `maxAge`  and not setting `expires` working as it seems you would expect it to (it doesn't require `expires`):

https://github.com/jshttp/cookie/blob/master/test/serialize.js#L99-L104

**Comment by bdombro** [comment]
Oh I actually see I made a mistake now -- I was passing an extremely high maxAge to Express, which calculates expires based on maxAge and it made an invalid date. So, it's good that your repo caught that :-). Thanks!
