### ISSUE TITLE
Support for Partitioned attribute

### ISSUE THREAD

**Issue by supersnager** [jshttp/cookie#147]
Hi, it would be great if the library supported the "Partitioned" attribute.
References:
https://developer.mozilla.org/en-US/docs/Web/Privacy/Partitioned_cookies
https://github.com/privacycg/CHIPS

**Comment by punithk** [comment]
Hi, I created a pull request adding support for this functionality along with tests: <https://github.com/jshttp/cookie/pull/151>

**Comment by misi** [comment]
I would be also happy if I can use this new attribute. @dougwilson is there anything I can help in it?

**Comment by nicob-29** [comment]
Google plan soon to activate the feature: https://privacysandbox.com/open-web/#the-privacy-sandbox-timeline
Any update ?

**Comment by nicob-29** [comment]
@dougwilson 
Thanks !
