### ISSUE TITLE
Setting domain on 'cookie'

### ISSUE THREAD

**Issue by scottishsmile** [jshttp/cookie#160]
Hi,

I am finding that the cookie created for example.com by default is not accepted if you enter www.example.com into the browser. Chrome/ Edge seems to be blocking it.

I have tried entering domain: 'www.example.com' but it is not having an effect?
```js
res.setHeader('Set-Cookie', [
cookie.serialize(
    `${COOKIE_NAME}`, accessJson, {
        httpOnly: true,
        domain: COOKIE_DOMAIN,
        secure: true,
        maxAge: COOKIE_MAX_AGE,
        sameSite: 'lax',
        path: '/'
    }
)]);
```
Anyone else having this issue?

**Comment by blakeembrey** [comment]
This is how cookies are designed to work from the [RFC](https://www.rfc-editor.org/rfc/rfc6265#section-5.3). You cannot set a cookie for a subdomain, but the reverse is allowed.

> If the canonicalized request-host does not domain-match the domain-attribute: Ignore the cookie entirely and abort these steps.

For domain matching:

> All of the following conditions hold:
> *  The domain string is a suffix of the string.
> * The last character of the string that is not included in the domain string is a %x2E (".") character.
> * The string is a host name (i.e., not an IP address).

Setting `www.example.com` from `example.com` is not a suffix of the string.
