### ISSUE TITLE
0.7.0 no longer supports `.localhost` domain value

### ISSUE THREAD

**Issue by EvHaus** [jshttp/cookie#173]
After upgrading from `0.6.0` to `0.7.0` this code no longer works:

```js
cookie.serialize('myCookie', 'some content', {
  domain: '.localhost',
  httpOnly: true,
  maxAge: 2147483647,
  path: '/',
  sameSite: 'lax',
  secure: true
});
```

This now throws `option domain is invalid`.

According [RFC6265 Section 4.1.2.3](https://www.rfc-editor.org/rfc/rfc6265#section-4.1.2.3) a leading `.` (dot) should be allowed for targeting subdomains. Am I doing something wrong, or is this a possible 0.7.0 bug?

**Comment by rdenman** [comment]
I'm running into this same issue, reverting back to `0.6.0` for now

**Comment by robsterlini** [comment]
We're running into a similar issue where our leading `.` is needed to support subdomains.

**Comment by EvHaus** [comment]
> Is that the language you are reading that the leading dot should be allowed, since I don't see your specific phrasing?

Correct.

> So it looks like the dot isn't required and isn't permitted in the spec for Set-Cookie

That's surprising to me. How would a cookie target all subdomains with it?

**Comment by blakeembrey** [comment]
> How would a cookie target all subdomains with it?

If you specify the domain, they automatically target all subdomains. It surprised me too. It's part of the `domain-match` part of the spec.

**Comment by blakeembrey** [comment]
Domain match: [5.1.3](https://www.rfc-editor.org/rfc/rfc6265#section-5.1.3). Building the cookie header is specified here: [5.4](https://www.rfc-editor.org/rfc/rfc6265#section-5.4). TL;DR: no domain = host-only, domain = send for this domain and any subdomain.

The leading dot behavior is from the earlier spec: https://datatracker.ietf.org/doc/html/rfc2109.

**Comment by blakeembrey** [comment]
Released a fix in https://github.com/jshttp/cookie/releases/tag/v0.7.1.
