### ISSUE TITLE
Cookie with same name from different domains

### ISSUE THREAD

**Issue by felipou** [jshttp/cookie#18]
Just a thought: if you set a cookie for a domain (for example: example.com) and then set a cookie for a subdomain (test.example.com), the next time you request something from the subdomain, both cookies (with the same name!!!) are sent to the server.

In the case of node-cookie, only the first cookie is parsed (the one that comes first in the Cookie header), the other is ignored.

I tried to find how this case should be handled by webservers in general, but couldn't, so I thought a good place to start gathering opinions and information would be here.

Should same name cookies really be ignored? Or should there be a way to retrieve all from the application?

**Comment by WormGirl** [comment]
I have the same problem, there is a domain 'a.b.com',we save a token named 'user_token' with domain('.b.com'),but one day the server operation and maintenance change the domain to 'a.sub.b.com', if code not be change, there will produce another 'user_token' with domain ('.sub.b.com'),If you have previously opened the website，now, open again，Two identical values ​​will appear，in chrome and safari, if we get the 'user_token' , we will get two result.
