### ISSUE TITLE
sameSite "Lax" doesn't work any more

### ISSUE THREAD

**Issue by ktdd** [jshttp/cookie#189]
In earlier versions of this library sameSite was parsed as opt.sameSite.toLowerCase(). In 1.0.0 toLowerCase() isn't called and it breaks.

Is the removal of toLowerCase() by design or a bug?

**Comment by blakeembrey** [comment]
It was changed by design and is noted in the release notes: https://github.com/jshttp/cookie/releases/tag/v1.0.0.

Do you have a use-case that requires non-lowercased string support? I'm not opposed to adding it back if needed.

**Comment by ktdd** [comment]
Damn, I read those release notes but apparently too fast.

@fastify/session was using Lax instead of lax in their code and I just wanted to confirm before entering an issue there, but it seems they already fixed their code and it's now using the lower case variant.
