### ISSUE TITLE
Option to return to old cookie validation regex

### ISSUE THREAD

**Issue by sgewirtz1** [jshttp/cookie#205]
We're from another team (approuter library) which is using the cookies library where most of our customers are all failing due to illegal characters (including commas) we are using the cookies library, is there no way to allow bypass of this validation in favor of the prior check?

**Comment by blakeembrey** [comment]
Closing as a duplicate of https://github.com/jshttp/cookie/issues/191, but it's not possible to revert entirely due to security issues.
