### ISSUE TITLE
Incorrect parsing of cookies

### ISSUE THREAD

**Issue by bytesnz** [jshttp/cookie#212]
Just came across a set-cookie header value that is not correctly parsed by 1.0.1. Presuming it is due to the HttpOnly attribute. I'm using cookie to parse cookies received during testing API endpoints in node, hence the receiving the HttpOnly attribute

```js
import cookie from 'cookie';

const cookies = cookie.parse('s=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx; Path=/; HttpOnly; SameSite=Strict, c=yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy; Path=/; HttpOnly; SameSite=Strict');
```

results in

```js
{
  s: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
  Path: '/',
  SameSite: 'Strict, c=yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy'
}
```

**Comment by wesleytodd** [comment]
This package does not *parse* the `set-cookie` header. https://github.com/jshttp/cookie?tab=readme-ov-file#cookieparsestr-options

**Comment by wesleytodd** [comment]
Maybe this will help? https://github.com/jshttp/cookie/pull/213

**Comment by wesleytodd** [comment]
No worries! It happens, and it spurred me to finally open that PR after seeing this question many times over many years. Cheers!
