### ISSUE TITLE
Doesn't parse cookies with no value

### ISSUE THREAD

**Issue by 0x8890** [jshttp/cookie#44]
Suppose I have a Cookie header like this:
```
Cookie: foo=bar; baz
```
What gets parsed is `{ foo: 'bar' }`, but I don't get `baz`. This should be a valid cookie header since I extracted it from something that Firefox sent out but replaced the keys and values.

**Comment by dougwilson** [comment]
Interesting. I'm out and about this weekend, but can you find the RFC that specifies this behavior, please?

**Comment by dougwilson** [comment]
The current RFC, 6265, requires the equal sign for the header to be valid (section 4.2.1).

**Comment by 0x8890** [comment]
Hmm, according to [section 5.2](https://tools.ietf.org/html/rfc6265#section-5.2) the user agent should completely ignore a parameter if `=` is missing, but I guess Firefox is relaxed about this. Will just use name/value since it's a gray area, thanks.
