### ISSUE TITLE
.parse missing HttpOnly and Secure

### ISSUE THREAD

**Issue by emilbayes** [jshttp/cookie#45]
Why are the HttpOnly and Secure flags missing? ((See test))[https://github.com/jshttp/cookie/blob/master/test/parse.js#L36]

I would have expected:

```js
{ foo: '%1', bar: 'bar', Secure: true, HttpOnly: true}
```

I haven't read the RFC so I don't know the details, but those two flags are useful when building a HTTP Agent

**Comment by hsablonniere** [comment]
Same question?

**Comment by dougwilson** [comment]
Hi! You are probably confusing the `Cookie` header and the `Set-Cookie` header; the `.parse` method of this module only parses the `Cookie` header. That example is just sitting there probably confusing you, as the `Cookie` header does not have that. The test may as well be `cookie.parse('foo=%1;bar=bar;hi;bye')`. If you would like to have a method to parse the `Set-Cookie` header, please, feel free to make a PR to implement this functionality :)
