### ISSUE TITLE
Parsing boolean values of a cookie

### ISSUE THREAD

**Issue by TimothyGu** [jshttp/cookie#49]
Hi,

When parsing a cookie with `HttpOnly` and/or `Secure` which don't have values, they are directly ignored.

```js
require('cookie').parse('SessionId=asdf2312fasdf; path=/; HttpOnly')
{ 'SessionId': 'asdf2312fasdf', path: '/' }
```

Would it be possible to make these attributes accessible?

**Comment by dougwilson** [comment]
Hi! This module only parses the Cookie HTTP request header. What you have there looks like the HTTP Set-Cookie response header, a very different header. You can either provide a PR to add this functionality as another parse function, or use a module that is designed to parse that header.

**Comment by TimothyGu** [comment]
Ah okay. I used a different method to fix the issue, but thanks for the explanation anyway.
