### ISSUE TITLE
use semver

### ISSUE THREAD

**Issue by danielb2** [jshttp/cookie#54]
Have you considered using semver?  bump it to 1.0 ?

**Comment by dougwilson** [comment]
This module does use semver. If you read the spec, it describes exactly what 0.x.y means. Now sure how we are not using semver.

**Comment by danielb2** [comment]
http://semver.org/#semantic-versioning-specification-semver

See point number 5

**Comment by danielb2** [comment]
and point number 4 as well. Is this not considered stable?

**Comment by dougwilson** [comment]
> Is this not considered stable?

Not currently, no. You should depend on a specific version while this module is fixed up into a 1.0 state.

**Comment by dougwilson** [comment]
Anyway, I still don't understand the original question:

> Have you considered using semver?

Along with the title:

> use semver

Can you elaborate on how we are not following semver?

**Comment by dougwilson** [comment]
Hi @danielb2, just wanted to ping you that the next release will be 1.0.0, if you were still adverse to using 0.y.z modules.

**Comment by dougwilson** [comment]
Sorry, there is the 0.3.0 release and then it turns 1.0.0, with some of the pending breaking changes and dropping older Node.js testing. Spoke just a little too soon :)

**Comment by nwalters512** [comment]
@dougwilson are you still planning on releasing `1.0.0`? As far as I can tell, there haven't been any breaking changes in many years.
