### ISSUE TITLE
Add support for "SameSite" attribute

### ISSUE THREAD

**Issue by lpfeup** [jshttp/cookie#55]
"Same-site cookies allow servers to mitigate the risk of CSRF and information leakage attacks by asserting that a particular cookie should only be sent with requests initiated from the same registrable domain."

https://tools.ietf.org/html/draft-west-first-party-cookies-06
https://www.chromestatus.com/feature/4672634709082112

**Comment by dougwilson** [comment]
We can probably work to add support for this attribute, sure! Before we start, can you explain what the difference between this attribute and the first-party-only one is? The abstract in the RFC drafts at least seem to be very similar.

**Comment by jltwoo** [comment]
It's just renaming, it's the same attribute

They renamed it due to legal reasons, because "party" is a legal term used for drafting laws... so "SameSite" was recommended instead to prevent confusion.
https://lists.w3.org/Archives/Public/ietf-http-wg/2016JanMar/0134.html

**Comment by dougwilson** [comment]
@jltwoo, ah, gotcha. So that asks the question for what we should do with the existing `firstPartyOnly` property. I can think of three options, and I'm not sure which is best:

1. Do nothing and have both of them.
2. Mark `firstPartyOnly` as deprecated and tell users to use `sameSite`, but take no actions.
3. Mark `firstPartyOnly` as deprecated, tell users to use `sameSite` and also set the same site flag.

Thoughts?

**Comment by wesleytodd** [comment]
I did some googling and couldn't find much information on the browser support for these to options.  Do you have that info @jltwoo?  If the browsers take either or none then I am in favor of 3 to get people using the correct flag.

This is the closes thing I could find that actually talks about how this will move forward: https://www.chromestatus.com/features/4672634709082112

**Comment by dougwilson** [comment]
So, circling back around on this issue, I did some digging around, and it looks like Chrome never actually shipped `First-Party-Only`, at least without requiring a flag set in the client. This means it is unlikely to actually have ever been accepted anywhere. With this module still at the `0.x` phase in semver, I move to just add same site, and simply drop first party only (which means supplying it in the option in version 0.3.0+ will just do nothing, as if the option didn't exist). Thoughts?

**Comment by lpfeup** [comment]
I am also in favor of deprecating `firstPartyOnly ` and just move to `sameSite`.

**Comment by jltwoo** [comment]
I agree with @dougwilson, if you follow the full thread here: 
https://bugs.chromium.org/p/chromium/issues/detail?id=459154

they never actually shipped it until Chrome 51
It would be safe to assume to just deprecate `First-Party-Only` support and adopt `SameSite` entirely
