### ISSUE TITLE
Option expires is invalid after parsing

### ISSUE THREAD

**Issue by XadillaX** [jshttp/cookie#61]
This package will check if it is a `Date` object when serializing `options.expires`.

But the result of `cookie.parse()` won't return a `Date` object.

So that situation will crash:

header:

```json
...,
"set-cookie": [
  "__cfduid=d9bd5542019f8c0f082ddfebd222d5f651480319196; expires=Tue, 28-Nov-17 07:46:36 GMT; path=/; domain=.whoishostingthis.com; HttpOnly"
],
```

code:

```javascript
...
foo.map(c => cookie.parse(););

...
foo.serialize(c => cookie.serialize());
```

**Comment by dougwilson** [comment]
The parse method parses the Cookie HTTP header, not the Set-Cookie HTTP header.
