### ISSUE TITLE
Comma separated cookie values

### ISSUE THREAD

**Issue by plcarmel** [jshttp/cookie#62]
Comma separated cookie values are not common but they are a valid http header. Right now they are not handled by the parse function.

**Comment by dougwilson** [comment]
Hi @plcarmel hm, I've never heard of that before. Can you fill me in on more details? Is there a specification for this somewhere? Right now we are parsing the `Cookie` header as it shows in https://tools.ietf.org/html/rfc6265#section-4.2.1 which only mentions a `;` separator character, not a `,` character.

**Comment by plcarmel** [comment]
It is a consequence of the rules governing the presence of multiple HTTP headers. It is possible to have multiple `Cookie` headers and it must be possible to combine them using a comma-separated list, therefore cookie values can be separated by commas.

https://tools.ietf.org/html/rfc2616

> Multiple message-header fields with the same field-name MAY be present in a message if and only if the entire field-value for that header field is defined as a comma-separated list [i.e., #(values)]. It MUST be possible to combine the multiple header fields into one "field-name: field-value" pair, without changing the semantics of the message, by appending each subsequent field-value to the first, each separated by a comma. The order in which header fields with the same field-name are received is therefore significant to the interpretation of the combined field value, and thus a proxy MUST NOT change the order of these field values when a message is forwarded.

However, it is not allowed (anymore) to fold multiple `Set-Cookie` headers because there is a conflict with the comma present in the date of "Expire".

https://tools.ietf.org/html/rfc6265

> Origin servers SHOULD NOT fold multiple Set-Cookie header fields into a single header field.  The usual mechanism for folding HTTP headers fields (i.e., as defined in [RFC2616]) might change the semantics of the Set-Cookie header field because the %x2C (",") character is used by Set-Cookie in a way that conflicts with such folding.

**Comment by plcarmel** [comment]
However,

https://tools.ietf.org/html/rfc6265

> When the user agent generates an HTTP request, the user agent MUST NOT attach more than one Cookie header field.

Ok, probably not legal. I will open an issue for Jetty instead, that generated the comma separated values.

**Comment by dougwilson** [comment]
Hi @plcarmel I see you're referencing both `Set-Cookie` and `Cookie` headers. The `parse()` function of this module only works for `Cookie`, not `Set-Cookie`. I'm not sure how all the `Set-Cookie` information is relevant here.

As far as I know, the spec does not allow more than a single `Cookie` header to be attached, so the folding mechanism doesn't apply here for the `Cookie` header, but I may be mistaken. Which web browsers are generated comma-separated or multiple `Cookie` headers?

**Comment by plcarmel** [comment]
I was referencing `Set-Cookie` as an exemple of an http header that cannot be present multiple times because of a semantic conflict.

I have a Jetty http server that I use to proxy requests to Ember Fastboot. The comma separated list of values happened while copying headers from the request to the response with an API that breaks down the cookie into individual values and an other API that recombines them using the usual HTTP mechanism, the comma.

**Comment by dougwilson** [comment]
Gotcha. As far as I know, that is completely out of spec, so I'm going to close as invalid.

**Comment by plcarmel** [comment]
Ok, I agree. Thank you for your time.

**Comment by jimmywarting** [comment]
I found this parser that states that comma separated set-cookies can occur. So it can also handle them. 
it have steadily increased in weekly downloads over npm and seems to become more popular 
https://github.com/nfriedly/set-cookie-parser/blob/master/lib/set-cookie.js#L115-L125

the fetch spec (Headers class) wants to join every set-cookie into a comma separated
so i think maybe it would be good if this cookie package could unfold them to co-work with node-fetch

**Comment by dougwilson** [comment]
This module does not provide a parser for set-cookie at all; there is no lack of support for comma-separated set-cookie headers that needs to be addressed since this module does not parse then even when no commas are there.
