### ISSUE TITLE
maxAge is wrong

### ISSUE THREAD

**Issue by patrikx3** [jshttp/cookie#65]
Hi! Just a small issue, I think maxAge is in seconds (RFC), but jshttp/cookie uses milliseconds.
As well in NPM is shows seconds, when in the cookie underlying implementation uses milliseconds.
https://tools.ietf.org/html/rfc7234#section-5.2.2.8 - seconds
https://www.npmjs.com/package/cookie - shows seconds

But when I uses it i have to use milliseconds.
( I divided by 1000 and it was wrong, so I tried with milliseconds and it works now. :) )

**Comment by dougwilson** [comment]
Yes, our API takes milliseconds, to make it easy to use with other JavaScript APIs taking milliseconds. What is written to the HTTP request is seconds, as the RFC requires, so there is no issue here.

**Comment by patrikx3** [comment]
Cool, just trying to help you so the docs in NPM and README will show milliseconds instead of seconds... It is not clear right now. But thanks.

**Comment by patrikx3** [comment]
ciao

**Comment by dougwilson** [comment]
Oh, sorry, I didn't realize you were actually describing a doc issue, because it sounded like you were talking about the RFC. I see in https://github.com/jshttp/cookie/blob/master/README.md#maxage it is wrong, yes. Please feel free to submit a PR :)

**Comment by patrikx3** [comment]
what do you mean? just fork , fix it and send you a pull??? that's what you mean?
