### ISSUE TITLE
Incosinstend documentation between npm and github

### ISSUE THREAD

**Issue by NickNaso** [jshttp/cookie#75]
Hi everyone,
I want report an inconsistency on documentation between npm https://www.npmjs.com/package/cookie and gitbuh repo.

On the github repo is psecioficed that the value of ```maxAge``` option need to be specified in **milliseconds** while on npm is specified that this value have to be set in **seconds**

I tried and found that the ```maxAge``` value need to be expressed in **milliseconds**

![screen shot 2018-04-09 at 12 54 00](https://user-images.githubusercontent.com/387506/38494533-8e16738a-3bf6-11e8-90c0-cdde69fa58fc.png)

<img width="1223" alt="screen shot 2018-04-09 at 12 55 51" src="https://user-images.githubusercontent.com/387506/38494513-78ef19c6-3bf6-11e8-909b-e01eff64dc94.png">

**Comment by dougwilson** [comment]
Yes, milliseconds is the correct one. It was just fixed in the readme recently:+1:
