### ISSUE TITLE
Maxage milliseconds confusion

### ISSUE THREAD

**Issue by microcipcip** [jshttp/cookie#78]
Hi, is Maxage definitely in milliseconds or in seconds? The example in the docs seems to indicate that it is in seconds... `maxAge: 60 * 60 * 24 * 7 // 1 week` this would be in seconds, not milliseconds.

**Comment by dougwilson** [comment]
It is milliseconds. Probably a mistake in the example if you want to fix :+1:

**Comment by microcipcip** [comment]
@dougwilson I wrote a script based on yours and in my demo (I just tested) the cookie is set in seconds in both node and the browser. See [express](https://github.com/microcipcip/cookie-universal/blob/master/packages/cookie-universal/demo/server-express.js) and [connect](https://github.com/microcipcip/cookie-universal/blob/master/packages/cookie-universal/demo/server.js) demos.

Here is the [relevant code](https://github.com/microcipcip/cookie-universal/blob/master/packages/cookie-universal/index.js#L59)

**Comment by dougwilson** [comment]
Gotcha. I guess I'm not understanding. Do you want to pull request the change?

**Comment by microcipcip** [comment]
Basically the docs say it is in milliseconds, however I am actually setting it in seconds, not milliseconds. So the docs should actually say that you have to set them in seconds and therefore the `maxAge: 60 * 60 * 24 * 7 // 1 week` example is actually correct. Hopefully it is more clear now :)

**Comment by dougwilson** [comment]
So the docs used to say seconds but other users told me it was milliseconds and I merged their pr https://github.com/jshttp/cookie/commit/f8a7e428164a3cbbbd5146a8b7051f27c9333d50

Was this incorrect?

**Comment by microcipcip** [comment]
From my findings I think they were. If you run my demo and open the browser it will correctly set the value using seconds, not milliseconds.

**Comment by dougwilson** [comment]
PR #66

**Comment by dougwilson** [comment]
So... I'm just really confused. I had the docs at seconds, was told by multiple people it was milliseconds and so now I'm just really confused. I don't want to keep going back and forth on this. Maybe I need some time to walk through the code (I'm not the original author) to understand the correct answer. I don't want to endlessly get issues saying it's seconds then milliseconds then seconds again, etc.

**Comment by dougwilson** [comment]
Issue #75 also thought it was supposed to be milliseconds as an example

**Comment by microcipcip** [comment]
Umm ok, I'll test with just with Cookie without my script and see what result I get back. Hopefully is not some kind of weird bug due to OS...

**Comment by dougwilson** [comment]
Cool. Yea, I'm not saying you're wrong at all, just really confused at this point.

**Comment by microcipcip** [comment]
I just realized that this script is used in express/cookie-parser, so definitely somebody would have spot an error like that. I see every express/cookie-parser example set in milliseconds, I'll double check my code, thanks :)

**Comment by microcipcip** [comment]
I copy pasted this code https://github.com/jshttp/cookie#example and I get 1 week....dunno what is going on, it seems definitely working in seconds not milliseconds lol

![img_005](https://user-images.githubusercontent.com/585402/39951188-691f8042-557f-11e8-9993-094fd7bce59b.jpg)
.

**Comment by dougwilson** [comment]
Thanks for checking. I guess the next person who says milliseconds I'll have to drill. Would you mind me at mentioning you when that happens at all? I can revert the merge of PR #66

**Comment by microcipcip** [comment]
I am very confused because express cookie-parser does work in milliseconds....
