### ISSUE TITLE
npm README has wrong link for RFC6265 hyperlinks

### ISSUE THREAD

**Issue by anderson-dan-w** [jshttp/cookie#80]
The README here on github has a link to RFC6265 for e.g. `Domain Set-Cookie attribute`, but somehow the link on the `npm` version of [README](https://www.npmjs.com/package/cookie#domain) is to RFC6266. Seems to happen for most/all of the links (`Expires`, `Max-Age`, `Path`).

Not sure if that's under control of the repo owner, or an issue on the `npm` side.

**Comment by dougwilson** [comment]
Huh, very strange. Let me know what I need to do to fix.

**Comment by anderson-dan-w** [comment]
Oh, no clue how to fix it :) - just started reading `npm` and came across the discrepancy. If you upload  the same README or if `npm` is pulling the README on its own (ie not something you supply), then the problem likely isn't on your end but theirs. Not sure what to do from there

**Comment by dougwilson** [comment]
Fixed in https://github.com/jshttp/cookie/commit/8bb4e19ac6ff253cc5541478282061d6a09a12fe :+1:
