### ISSUE TITLE
Parsing cookie seems to change strings

### ISSUE THREAD

**Issue by PSPanesar** [jshttp/cookie#82]
Hi,

I've used the cookie.parse function to parse a cookie to extract a string. I've notice though that it has changed the % to a :. for example:

Original string in cookie: s%3AYICgq7xLgu5NOy

Parsed string: s:YICgq7xLgu5NOy

Could anyone help by letting me know what the start of the string is parsed incorrectly?

Bw

**Comment by dougwilson** [comment]
https://github.com/jshttp/cookie/blob/master/README.md#decode
