### ISSUE TITLE
Having problems parsing the cookie my server sends (unmodified)

### ISSUE THREAD

**Issue by Alanz2223** [jshttp/cookie#83]
Hello, I have a express.js server with connect-session and it sends a cookie that looks like this

`"language=en-US; Path=/, keystone.uid=s%3A5b4f9dc45e23fe02b4b24862%3ACzrzXyYInv7VKl5PaevC9Ynd1qJD72Ip%2BmCd7NynoxU.rGWyRaQecitVOH4vQpZTD1ThpvQ44BI%2BmzOF51kjSms; Max-Age=864; Path=/; Expires=Wed, 25 Jul 2018 19:07:02 GMT; HttpOnly, this.sid=s%3AappByhX2Ao31t5RlBF9cd80lZcsQEjE3.o4Wq9o7bhpptCrcJt6XIh1jjKQgWPgibnoI8TDalkDk; Path=/; Expires=Thu, 25 Jul 2019 18:52:38 GMT; HttpOnly"`

I then store that string and whenever I try to parse it with this module, it gives me the following object

`{ language: 'en-US',

  Path: '/, 
keystone.uid=s:5b4f9dc45e23fe02b4b24862:CzrzXyYInv7VKl5PaevC9Ynd1qJD72Ip+mCd7NynoxU.rGWyRaQecitVOH4vQpZTD1ThpvQ44BI+mzOF51kjSms',

  'Max-Age': '864',

  Expires: 'Wed, 25 Jul 2018 19:07:02 GMT',

  'HttpOnly, 
this.sid': 's:appByhX2Ao31t5RlBF9cd80lZcsQEjE3.o4Wq9o7bhpptCrcJt6XIh1jjKQgWPgibnoI8TDalkDk' }`

The cookie is passed without the quotes of course. I am trying to extract the this.sid value. Is this a limitation of this parser or are the cookies my server is sending wrong?

**Comment by dougwilson** [comment]
The string you are showing is the `Set-Cookie` header format. This module doesn't parse `Set-Cookie` strings, just the string of the `Cookie` header.

**Comment by Alanz2223** [comment]
Ah, I was unaware of the difference. Thank you for your time and for pointing this out.

**Comment by dougwilson** [comment]
No problem at all. The way it was initially formatted, it was hard to tell what was happening, but then noticed that there was a comma `,` in there, which is just a valid part of a value in the `Cookie` header, with the `;` being a key pair separator. So just replacing the `;` with `\n` gives:

```
language=en-US
Path=/, keystone.uid=s%3A5b4f9dc45e23fe02b4b24862%3ACzrzXyYInv7VKl5PaevC9Ynd1qJD72Ip%2BmCd7NynoxU.rGWyRaQecitVOH4vQpZTD1ThpvQ44BI%2BmzOF51kjSms; Max-Age=864
Path=/
Expires=Wed, 25 Jul 2018 19:07:02 GMT
HttpOnly, this.sid=s%3AappByhX2Ao31t5RlBF9cd80lZcsQEjE3.o4Wq9o7bhpptCrcJt6XIh1jjKQgWPgibnoI8TDalkDk
Path=/
Expires=Thu, 25 Jul 2019 18:52:38 GMT
HttpOnly
```
