### ISSUE TITLE
Not compliant with rfc6265

### ISSUE THREAD

**Issue by reinier-vegter** [jshttp/cookie#86]
https://github.com/jshttp/cookie/blob/ddb7bbd899f0f0ce42db664884f4ff7b6d3076c6/index.js#L56

From RFC:

>  cookie-value      = *cookie-octet / ( DQUOTE *cookie-octet DQUOTE )
>  cookie-octet      = %x21 / %x23-2B / %x2D-3A / %x3C-5B / %x5D-7E
>                        ; US-ASCII characters excluding CTLs,
>                        ; whitespace DQUOTE, comma, semicolon,
>                        ; and backslash

So a value may be wrapped in quotes. If so, this parser will handle the quotes as part of the value.
Small thing, but it would be better to fix this, improving reliability, and to mention the RFC's this code is compliant with in the inline comments. Better, rename 'parse()' to 'parse_rfc6265()' or something.

Nevertheless, thanks for writing this in the first place, makes all of our lives a bit easier :+1:

**Comment by dougwilson** [comment]
Quotes are removed from the vales just a few lines down.
