### ISSUE TITLE
SameSite=None support needs to be released

### ISSUE THREAD

**Issue by kashiif** [jshttp/cookie#93]
With Google's announcement of Chrome 80 defaulting to `SameSite=Lax`, the support for `SameSite=None` is much needed.

I can see there have been some work on it. Kindly consider releasing it.

**Comment by dougwilson** [comment]
It has been released long ago. What version  are you using and what troubles are you having?

**Comment by kashiif** [comment]
Thanks for replying. I messed up. It's the `cookie-parser`'s old version bringing `cookie@0.3.1` into my yarn.lock file. Apologies.
