### ISSUE TITLE
EncodeURIComponent() applied partially in the function "serialize"

### ISSUE THREAD

**Issue by Konstantin-Sharohin** [jshttp/cookie#95]
**Hello!**

My system:

- macOS Mojave 10.14.6, 
- Google Chrome version 79.0.3945.130 (Official Build) 64-bit,
- React 16.11.0,
- react-cookie: 4.0.3,
- cookie 0.4.0.

I'm using your library and I think there might be an issue with the method "cookie.serialize" - it returns a string, that is not a valid HTTP header value and is not accepted by the browser.

How to reproduce:

1. Pass to the "serialize()" arguments like `"name", "value", {path:"/",maxAge: 86400000,domain:"localhost",secure:true,sameSite:true}`,
2. Get the returned value,
3. Try to set the document.cookie as the returned value of the "serialize()".

During debugging I've found that in the "serialize()" the method "encodeURIComponent()" is applied only to the "value" component (please see the screenshot below) 

<img width="597" alt="Screen Shot 2020-01-23 at 23 37 20" src="https://user-images.githubusercontent.com/45078528/73029214-d07df980-3e3f-11ea-8223-74bc778e6b1b.png">

what in turn results in impossibility of setting that cookie in the document (I've tested in Safari  13.0.4 as well). So the browser simply ignores the returned cookie and sets it as "" (empty string). 

But when I apply the "encodeURIComponent()" at the end on the resulting string (name + value + options) - browser accepts it.

**Thank you!**
_Sincerely,
Konstantin_

**Comment by dougwilson** [comment]
Thanks for the report, but I'm afraid I don't understand the issue. Can you provide a complete server that replicates the issue so I can see it not working in the web browser? Or maybe can you show what the value looks like and show where the violation of the RFC is occurring?

**Comment by dougwilson** [comment]
I'm also confused when you're talking about `document.cookie` as this is not a web browser module but is for running on the server side with Node.js.

**Comment by Konstantin-Sharohin** [comment]
I apologize, it looks like I've targeted server side package instead of the web client.

Thank you anyway!
