### ISSUE TITLE
Support flags in the cookie parser

### ISSUE THREAD

**Issue by viegasdom** [jshttp/cookie#96]
It seems `cookie` doesn't currently support parsing flags.

## Example
```
var cookie = require('cookie');
var setCookie = cookie.serialize('foo', 'bar', {secure: true});
// 'foo=bar; Secure'
var cookies = cookie.parse(setCookie);
// {foo: 'bar'}
```

Is this the expected behaviour?

**Comment by dougwilson** [comment]
Hello! This is because `cookie.parse` is

> Parse an HTTP Cookie header 

And the HTTP Cookie header format is `name=value; name2=value2`.

**Comment by dougwilson** [comment]
The `cookie.serialize` is

> Serialize a cookie name-value pair into a Set-Cookie header string.

Thus since it produces a string that is for a different HTTP header, they don't parse each other. This is because this module is for the Node.js server-side, which receives `Cookie` header in requests and generates `Set-Cookie` headers in the response.
