### ISSUE TITLE
Export statement should be placed at the bottom of the script for editor support

### ISSUE THREAD

**Issue by tim-kilian** [jshttp/cookie#97]
Hello,
Intellij can not recognize the function of the cookie object, when the methods are not defined before the export statement. In this case these two lines should be flipped, so they are in the right order. First declaration, then assignment.

```js
// ...

exports.parse = parse;
exports.serialize = serialize;
```

**Comment by dougwilson** [comment]
Thanks, but I prefer them to be at the top so seeing them is obvious. It is 100% valid comon JS export usage and javascript. It sounds like perhaps a bug should be reported to your editor, unless you can provide official documentation from your editor that says this is required.

**Comment by wesleytodd** [comment]
> I prefer them to be at the top so seeing them is obvious.

👍 

I agree strongly with @dougwilson, and also want to point out that if your IDE does not parse this correctly that is a bug with the editor.
